/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistema.supermercado;

import java.util.ArrayList;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.time.LocalDateTime;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author grupo1
 */
public class JFrame_registrarCompra extends javax.swing.JFrame {

    private ArrayList<Cliente> listaClientes;
    private ArrayList<Producto> listaProductos;
    private ArrayList<Cajero> listaCajeros;
    private Jframe_Menu menu;
    private Cliente clienteActual;
    private Compra compraActual;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_registrarCompra.class.getName());

    /**
     * Creates new form JFrame_registrarCompra
     */
    public JFrame_registrarCompra(ArrayList<Cliente> listaClientes,
            ArrayList<Producto> listaProductos,
            ArrayList<Cajero> listaCajeros,
            Jframe_Menu menu) {
        initComponents();

        ImageIcon original = new ImageIcon(getClass().getResource("/sistema/supermercado/imagenes/flecha retroceso.png"));
        Image escalada = original.getImage().getScaledInstance(24, 24, Image.SCALE_SMOOTH);
        botonVolverMenu.setIcon(new ImageIcon(escalada));

        this.listaClientes = listaClientes;
        this.listaProductos = listaProductos;
        this.listaCajeros = listaCajeros;
        this.menu = menu;

        cargarCajeros();
        cargarProductos();
        campoCedula.setEditable(true);
    }

    private void cargarCajeros() {
        comboCajero.removeAllItems();
        for (Cajero datoCajero : listaCajeros) {
            comboCajero.addItem(datoCajero.getNombre() + " " + datoCajero.getApellido());
        }
    }

    private void cargarProductos() {
        comboProducto.removeAllItems();
        for (Producto datoProducto : listaProductos) {
            comboProducto.addItem(datoProducto.getNombreProducto() + " - $" + datoProducto.getPrecio());
        }
    }

    private void habilitarEdicionCliente(boolean habilitar) {
        campoNombre.setEditable(habilitar);
        campoApellido.setEditable(habilitar);
        campoCorreo.setEditable(habilitar);
        campoTelefono.setEditable(habilitar);
        botonRegistrarCliente.setEnabled(habilitar);
    }

    private int generarNumeroCompra() {
        int totalCompras = 0;
        for (Cliente datoCliente : listaClientes) {
            totalCompras = totalCompras + datoCliente.getListaDeCompras().size();
        }
        return totalCompras + 1;
    }

    private void limpiarFormulario() {
        campoCedula.setSelectedItem("");
        campoNombre.setText("");
        campoApellido.setText("");
        campoCorreo.setText("");
        campoTelefono.setText("");
        campoPuntos.setText("");
        campoTotal.setText("");
        habilitarEdicionCliente(false);

        DefaultTableModel modeloFactura = (DefaultTableModel) tablaFactura.getModel();
        modeloFactura.setRowCount(0);

        clienteActual = null;
        compraActual = null;
    }

    private boolean validarCedula(String cedulaIngresada) {
        return cedulaIngresada.matches("\\d{10}");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonVolverMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoCedula = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        campoCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        campoPuntos = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        botonRegistrarCliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboCajero = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        comboProducto = new javax.swing.JComboBox<>();
        botonAnadir = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFactura = new javax.swing.JTable();
        campoTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        botonFinalizarCompra = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RegistrarCompra");

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        botonVolverMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/supermercado/imagenes/flecha retroceso.png"))); // NOI18N
        botonVolverMenu.addActionListener(this::botonVolverMenuActionPerformed);

        jLabel1.setFont(new java.awt.Font("Candara", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Compra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(botonVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel3.setText("Ingrese CI o RUC:");

        campoCedula.addActionListener(this::campoCedulaActionPerformed);

        jLabel8.setText("Datos del cliente");

        jPanel2.setBackground(new java.awt.Color(235, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel4.setText("Apellidos");

        campoNombre.setEditable(false);

        jLabel5.setText("Teléfono/Celular");

        jLabel6.setText("Nombres ");

        campoApellido.setEditable(false);

        campoCorreo.setEditable(false);
        campoCorreo.addActionListener(this::campoCorreoActionPerformed);

        jLabel9.setText("Correo electrónico");

        campoTelefono.setEditable(false);

        campoPuntos.setEditable(false);
        campoPuntos.addActionListener(this::campoPuntosActionPerformed);

        jLabel10.setText("Puntos SuperPOO");

        botonRegistrarCliente.setBackground(new java.awt.Color(51, 153, 0));
        botonRegistrarCliente.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        botonRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarCliente.setText("Registrar cliente");
        botonRegistrarCliente.setAlignmentY(0.0F);
        botonRegistrarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        botonRegistrarCliente.setEnabled(false);
        botonRegistrarCliente.addActionListener(this::botonRegistrarClienteActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(campoPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(campoApellido))))
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoPuntos)
                    .addComponent(botonRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        jLabel11.setText("Datos de la compra");

        jLabel12.setText("Cajero");

        jLabel13.setText("Producto");

        comboProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        botonAnadir.setBackground(new java.awt.Color(51, 153, 0));
        botonAnadir.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        botonAnadir.setForeground(new java.awt.Color(255, 255, 255));
        botonAnadir.setText("Añadir");
        botonAnadir.setAlignmentY(0.0F);
        botonAnadir.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        botonAnadir.addActionListener(this::botonAnadirActionPerformed);

        botonBuscar.setBackground(new java.awt.Color(51, 153, 0));
        botonBuscar.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("Buscar");
        botonBuscar.setAlignmentY(0.0F);
        botonBuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        botonBuscar.addActionListener(this::botonBuscarActionPerformed);

        jLabel14.setText("Detalle de la compra");

        jPanel5.setBackground(new java.awt.Color(235, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaFactura);

        campoTotal.setEditable(false);
        campoTotal.addActionListener(this::campoTotalActionPerformed);

        jLabel15.setText("Total");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(campoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        botonFinalizarCompra.setBackground(new java.awt.Color(51, 153, 0));
        botonFinalizarCompra.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        botonFinalizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        botonFinalizarCompra.setText("Finalizar compra");
        botonFinalizarCompra.setAlignmentY(0.0F);
        botonFinalizarCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        botonFinalizarCompra.addActionListener(this::botonFinalizarCompraActionPerformed);

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(this::botonLimpiarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 23, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(botonFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(comboCajero, 0, 181, Short.MAX_VALUE)
                    .addComponent(comboProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(botonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverMenuActionPerformed
        // TODO add your handling code here:
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverMenuActionPerformed

    private void campoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaActionPerformed

    private void botonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarClienteActionPerformed
        // TODO add your handling code here:
        String cedulaIngresada = String.valueOf(campoCedula.getEditor().getItem()).trim();
        String nombreIngresado = campoNombre.getText().trim();
        String apellidoIngresado = campoApellido.getText().trim();
        String correoIngresado = campoCorreo.getText().trim();
        String telefonoIngresado = campoTelefono.getText().trim();

        if (cedulaIngresada.isEmpty() || nombreIngresado.isEmpty() || apellidoIngresado.isEmpty()
                || correoIngresado.isEmpty() || telefonoIngresado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los datos del cliente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCedula(cedulaIngresada)) {
            JOptionPane.showMessageDialog(this, "La cédula debe tener exactamente 10 números.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Cliente clienteNuevo = new Cliente(cedulaIngresada, nombreIngresado, apellidoIngresado,
                telefonoIngresado, 0, correoIngresado);

        listaClientes.add(clienteNuevo);
        clienteActual = clienteNuevo;

        habilitarEdicionCliente(false);
        JOptionPane.showMessageDialog(this, "Cliente registrado correctamente.");

    }//GEN-LAST:event_botonRegistrarClienteActionPerformed

    private void campoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCorreoActionPerformed

    private void campoPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPuntosActionPerformed

    private void botonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnadirActionPerformed
        // TODO add your handling code here:
        if (clienteActual == null) {
            JOptionPane.showMessageDialog(this, "Primero busque o registre un cliente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int posicionProducto = comboProducto.getSelectedIndex();
        if (posicionProducto == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Producto productoSeleccionado = listaProductos.get(posicionProducto);

        if (!productoSeleccionado.verificarStockDisponible(1)) {
            JOptionPane.showMessageDialog(this, "No hay stock disponible de " + productoSeleccionado.getNombreProducto() + ".", "Sin stock", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (compraActual == null) {
            compraActual = new Compra(generarNumeroCompra(), LocalDateTime.now());
        }

        compraActual.agregarProducto(productoSeleccionado);

        DefaultTableModel modeloFactura = (DefaultTableModel) tablaFactura.getModel();
        modeloFactura.addRow(new Object[]{
            productoSeleccionado.getCodigo(),
            productoSeleccionado.getNombreProducto(),
            String.format("$%.2f", productoSeleccionado.getPrecio())
        });

        campoTotal.setText(String.format("$%.2f", compraActual.calcularTotal()));

    }//GEN-LAST:event_botonAnadirActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        String cedulaIngresada = String.valueOf(campoCedula.getEditor().getItem()).trim();

        if (cedulaIngresada.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una cédula o RUC.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCedula(cedulaIngresada)) {
            JOptionPane.showMessageDialog(this, "La cédula debe tener exactamente 10 números.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Cliente clienteEncontrado = null;
        for (Cliente datoCliente : listaClientes) {
            if (datoCliente.getCedula().equals(cedulaIngresada)) {
                clienteEncontrado = datoCliente;
                break;
            }
        }
        if (clienteEncontrado != null) {
            clienteActual = clienteEncontrado;
            campoNombre.setText(clienteActual.getNombre());
            campoApellido.setText(clienteActual.getApellido());
            campoCorreo.setText(clienteActual.getCorreo());
            campoTelefono.setText(clienteActual.getTelefono());
            campoPuntos.setText(String.valueOf(clienteActual.getPuntos()));
            habilitarEdicionCliente(false);
        } else {
            int respuesta = JOptionPane.showConfirmDialog(this,
                    "Cliente no encontrado. ¿Desea registrarlo?",
                    "Cliente nuevo", JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                clienteActual = null;
                campoNombre.setText("");
                campoApellido.setText("");
                campoCorreo.setText("");
                campoTelefono.setText("");
                campoPuntos.setText("0");
                habilitarEdicionCliente(true);
            }
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTotalActionPerformed

    private void botonFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarCompraActionPerformed
        // TODO add your handling code here:
        if (clienteActual == null) {
            JOptionPane.showMessageDialog(this, "Primero busque o registre un cliente.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (compraActual == null || compraActual.getListaDeProductosComprados().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Añada al menos un producto.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int posicionCajero = comboCajero.getSelectedIndex();
        if (posicionCajero == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un cajero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cajero cajeroSeleccionado = listaCajeros.get(posicionCajero);

        for (Producto datoProducto : compraActual.getListaDeProductosComprados()) {
            datoProducto.descontarStock(1);
        }

        clienteActual.agregarCompra(compraActual);
        cajeroSeleccionado.registrarVenta(compraActual);

        float totalCompra = compraActual.calcularTotal();
        int puntosGanados = (int) totalCompra;
        clienteActual.acumularPuntos(puntosGanados);

        JOptionPane.showMessageDialog(this,
                "Compra N° " + compraActual.getNumeroCompra() + " registrada con éxito.\n"
                + "Cliente: " + clienteActual.getNombre() + " " + clienteActual.getApellido() + "\n"
                + "Cajero: " + cajeroSeleccionado.getNombre() + " " + cajeroSeleccionado.getApellido() + "\n"
                + "Total: " + String.format("$%.2f", totalCompra) + "\n"
                + "Puntos ganados: " + puntosGanados);
    }//GEN-LAST:event_botonFinalizarCompraActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();


    }//GEN-LAST:event_botonLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnadir;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonFinalizarCompra;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonRegistrarCliente;
    private javax.swing.JButton botonVolverMenu;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JComboBox<String> campoCedula;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPuntos;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JTextField campoTotal;
    private javax.swing.JComboBox<String> comboCajero;
    private javax.swing.JComboBox<String> comboProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFactura;
    // End of variables declaration//GEN-END:variables
}
